In [3]:
import pandas as pd
import re
import numpy as np
from bs4 import BeautifulSoup
import time
import requests

# En este notebook vamos a recopilar datos y convertirlos en csv  
# para posteriormente juntarlos y analizarlos

In [ ]:
animes_csv = pd.read_csv('C:/Users/andre\Desktop\Curso_Data_Analytics\Tercera Semana\Proyecto Anime/anime.csv')
animes_csv.head()

,anime_id,name,genre,type,episodes,rating,members
0,32281,Kimi no Na wa.,"Drama, Romance, School, Supernatural",Movie,1,9.37,200630
1,5114,Fullmetal Alchemist: Brotherhood,"Action, Adventure, Drama, Fantasy, Magic, Mili...",TV,64,9.26,793665
2,28977,Gintama°,"Action, Comedy, Historical, Parody, Samurai, S...",TV,51,9.25,114262
3,9253,Steins;Gate,"Sci-Fi, Thriller",TV,24,9.17,673572
4,9969,Gintama&#039;,"Action, Comedy, Historical, Parody, Samurai, S...",TV,51,9.16,151266

In [77]:
url = "https://myanimelist.net/topanime.php"
response = requests.get(url)
response

In [17]:
soup = BeautifulSoup(response.content, "html.parser")
soup

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html class="appearance-none" lang="en">
<head>
<link crossorigin="anonymous" href="//www.googletagmanager.com/" rel="preconnect"/>
<link crossorigin="anonymous" href="https://cdn.myanimelist.net" rel="preconnect"/>
<title>
  Top Anime - MyAnimeList.net
</title>
<meta content="Browse the highest-ranked anime on MyAnimeList, the internet's largest anime database. Find the top TV series, movies, and OVAs right here!" name="description"/>
<meta content="anime, myanimelist, anime news, manga" name="keywords"/>
<link href="https://myanimelist.net/topanime.php?limit=50" rel="next"/>
<meta content="en_US" property="og:locale"/><meta content="360769957454434" property="fb:app_id"/><meta content="MyAnimeList.net" property="og:site_name"/><meta content="summary" name="twitter:card"/><meta content="@myanimelist" name="twitter:site"/><meta content=" Top Anime - MyAnimeList.net " property="og:title"/><meta content="https://cdn.myanimelist.net/img/sp/icon/apple-touch-icon-256.png" property="og:image"/><meta content="https://cdn.myanimelist.net/img/sp/icon/apple-touch-icon-256.png" name="twitter:image:src"/><meta content="https://myanimelist.net/topanime.php" property="og:url"/><meta content="Browse the highest-ranked anime on MyAnimeList, the internet's largest anime database. Find the top TV series, movies, and OVAs right here!" property="og:description"/>
<meta content="default" name="referrer"/><link href="/manifest.json" rel="manifest"/>
<meta content="ba61e914b8cda00bb1c55fec2395e027750e5f28" name="csrf_token"/>
<meta content="1e927243-8e02-48e3-b098-a7b78c5b4e36" name="fo-verify"/><meta content="initial-scale=1" name="viewport"><script src="https://cdn.myanimelist.net/static/viewer/js/logpose.min.js?v=20250929-8"></script>
<script defer="" src="https://cdn.myanimelist.net/static/viewer/js/logpose.global.js?v=20250929-8"></script>
<link as="style" href="https://cdn.myanimelist.net/static/assets/css/pc/style-710d81a83e.css" rel="preload">
<link as="style" href="https://cdn.myanimelist.net/static/assets/css/pc/dark-589cb567fb.css" rel="preload"/>
<link as="script" href="https://cdn.myanimelist.net/static/assets/js/pc/header-f5baf24c79.js" rel="preload"/>
<link as="script" href="https://cdn.myanimelist.net/static/assets/js/pc/all-9de2ec12ad.js" rel="preload"/>
<link href="https://cdn.myanimelist.net/static/assets/css/pc/style-710d81a83e.css" rel="stylesheet" type="text/css"/>
<link href="https://cdn.myanimelist.net/static/assets/css/pc/dark-589cb567fb.css" rel="stylesheet" type="text/css"/>
<script src="https://cdn.myanimelist.net/static/assets/js/pc/header-f5baf24c79.js" type="text/javascript"></script>
<script async="async" data-params='{"origin_url":"https:\/\/myanimelist.net"}' id="alljs" src="https://cdn.myanimelist.net/static/assets/js/pc/all-9de2ec12ad.js" type="text/javascript"></script>
<link href="https://myanimelist.net/plugins/myanimelist.xml" rel="search" title="MyAnimeList" type="application/opensearchdescription+xml"/>
<link href="https://cdn.myanimelist.net/images/favicon.ico" rel="shortcut icon" sizes="any" type="image/vnd.microsoft.icon"/>
<link href="https://cdn.myanimelist.net/images/favicon.svg" rel="icon" sizes="any" type="image/svg+xml"/>
<meta content="6Ld_1aIZAAAAAF6bNdR67ICKIaeXLKlbhE7t2Qz4" name="recaptcha_site_key"/>
<script>
window.GRECAPTCHA_SITE_KEY = '6Ld_1aIZAAAAAF6bNdR67ICKIaeXLKlbhE7t2Qz4';
</script>
<script async="" defer="" src="https://www.google.com/recaptcha/api.js?render=6Ld_1aIZAAAAAF6bNdR67ICKIaeXLKlbhE7t2Qz4"></script>
<link href="https://fonts.googleapis.com/css?family=Roboto:400,700&amp;display=swap" rel="stylesheet"/><script src="https://cdn.myanimelist.net/js/quantcast_choice.js?v=1760964835" type="text/javascript"></script>
<script src="https://cdn.myanimelist.net/js/cmp.js?v=1760964835" type="text/javascript"></script>
<script async="" src="https://btloader.com/tag?o=5110059113906176&amp;upapi=true"></script>
<!--<script src="https://hb.vntsm.com/v3/live/ad-manager.min.js" type="text/javascript" data-site-id="65a1835ac178db4aeb9540ce" data-mode="scan" async></script>-->
<script>
  var clientDarkMode = window.matchMedia("(prefers-color-scheme:dark)").matches;
  let darkMode = false

  if (clientDarkMode) {
    if (!$('html').hasClass("appearance-light")) { // SystemSetting = Dark && MAL UserSettings != Light
      darkMode = true
    }
  } else if ($('html').hasClass("appearance-dark")) { // MAL UserSettings = Dark
    darkMode = true
  }

    if (darkMode) {
    $('html').addClass("dark-mode");
  }
    $(document).ready(function() {
    if (darkMode) {
      if($('.js-color-pc-constant').length){$('.js-color-pc-constant').addClass("color-pc-constant");}
    }
  });

    window.stripeConfig = {
    disabled: false,
    maintenanceMessage: ""
  };
</script>
</link></meta></head>
<body class="page-common" data-country-code="ES" data-ms="true" data-time="1760964835" onload=" ">
<div id="myanimelist">
<script type="text/javascript">
    window.MAL.SkinAd.prepareForSkin('');
  </script>
<div class="ad-skin-side-outer ad-skin-side-bg bg-left" id="ad-skin-bg-left">
<div class="ad-skin-side left" id="ad-skin-left" style="display: none;">
<div id="ad-skin-left-absolute-block">
<div id="ad-skin-left-fixed-block"></div>
</div>
</div>
</div>
<div class="wrapper"><div class="" id="headerSmall"><a class="link-mal-logo" href="/">MyAnimeList.net</a> <script>(deployads = window.deployads || []).disablePageSegmentSessionTracking = true; </script>
<script>(deployads = window.deployads || []).pageSegment = 'top_anime';</script>
<script>
    var trackOutboundLink = function(url) {
        if (typeof ga !== 'undefined') {
            ga('send', 'event', 'outbound', 'click', url, {
                'transport': 'beacon',
                'hitCallback': function(){return true;}
            });
        }
    }
</script><div class="banner-header-anime-straming header-mini-banner" style="right:480px;">
<a href="https://mxj.myanimelist.net/" onclick="trackOutboundLink('https://mxj.myanimelist.net/')">
<img alt="MAL x JAPAN" height="36" src="/c/img/images/event/20210527_MALxJAPAN_MiniBanner/500x72_miniBanner_B.png" title="MAL x JAPAN" width="250"/>
</a>
</div>
<div id="header-menu"><div class="header-menu-login"><a class="btn-mal-service ga-click ga-impression" data-ga-click-type="hide-ads" data-ga-impression-type="hide-ads" href="https://myanimelist.net/membership?_location=mal_h_u" onclick="ga_mal_banner()">Hide Ads</a><a class="btn-login" href="https://myanimelist.net/login.php?from=%2Ftopanime.php" id="malLogin" onclick="ga_notlogin()">Login</a><a class="btn-signup" href="https://myanimelist.net/register.php?from=%2Ftopanime.php" onclick="ga_registration()">Sign Up</a></div></div></div> <div class="" id="menu">
<div id="menu_right"><script id="incremental-result-item-anime" type="text/x-template"><div class="list anime" :class="{'focus': focus}"><a :href="url" class="clearfix"><div class="on" v-if="focus"><span class="image" :style="{'background-image': 'url(' + item.image_url + ')'}"></span><div class="info anime"><div class="name">${ item.name } <span class="media-type">(${ item.payload.media_type })</span></div><div class="extra-info">Aired: ${ item.payload.aired }<br>Score: ${ item.payload.score }<br>Status: ${ item.payload.status }</div></div></div><div class="off" v-if="!focus"><span class="image" :style="{'background-image': 'url(' + item.thumbnail_url + ')'}"></span><div class="info anime"><div class="name">${ item.name }</div><div class="media-type">(${ mediaTypeWithStartYear })</div></div></div></a></div></script><script id="incremental-result-item-manga" type="text/x-template"><div class="list manga" :class="{'focus': focus}"><a :href="url" class="clearfix"><div class="on" v-if="focus"><span class="image" :style="{'background-image': 'url(' + item.image_url + ')'}"></span><div class="info manga"><div class="name">${ item.name } <span class="media-type">(${ item.payload.media_type })</span></div><div class="extra-info">Published: ${ item.payload.published }<br>Score: ${ item.payload.score }<br>Status: ${ item.payload.status }</div></div></div><div class="off" v-if="!focus"><span class="image" :style="{'background-image': 'url(' + item.thumbnail_url + ')'}"></span><div class="info manga"><div class="name">${ item.name }</div><div class="media-type">(${ mediaTypeWithStartYear })</div></div></div></a></div></script><script id="incremental-result-item-character" type="text/x-template"><div class="list character" :class="{'focus': focus}"><a :href="url" class="clearfix"><div class="on" v-if="focus"><span class="image" :style="{'background-image': 'url(' + item.image_url + ')'}"></span><div class="info character"><div class="name"  v-html="item.name"></div><div class="extra-info"><ul class="related-works"><li v-for="work in item.payload.related_works" class="fs-i">- ${ work }</li></ul>Favorites: ${ item.payload.favorites }</div></div></div><div class="off" v-if="!focus"><span class="image" :style="{'background-image': 'url(' + item.thumbnail_url + ')'}"></span><div class="info character"><div class="name"  v-html="item.name"></div></div></div></a></div></script><script id="incremental-result-item-person" type="text/x-template"><div class="list person" :class="{'focus': focus}"><a :href="url" class="clearfix"><div class="on" v-if="focus"><span class="image" :style="{'background-image': 'url(' + item.image_url + ')'}"></span><div class="info person"><div class="name">${ item.name }</div><div class="extra-info"><span v-if="item.payload.alternative_name">${ item.payload.alternative_name }<br></span>Birthday: ${ item.payload.birthday }<br>Favorites: ${ item.payload.favorites }</div></div></div><div class="off" v-if="!focus"><span class="image" :style="{'background-image': 'url(' + item.thumbnail_url + ')'}"></span><div class="info person"><div class="name">${ item.name }</div></div></div></a></div></script><script id="incremental-result-item-company" type="text/x-template"><div class="list company" :class="{'focus': focus}"><a :href="url" class="clearfix"><div class="on" v-if="focus"><span class="image" :style="{'background-image': 'url(' + item.image_url + ')'}"></span><div class="info company"><div class="name">${ item.name }</div><div class="extra-info"><span v-if="item.payload.japanese">(${ item.payload.japanese })<br></span>
                        Anime titles: ${ item.payload.num_animes.toLocaleString() }<br>
                        Favorites: ${item.payload.favorites.toLocaleString()}
                    </div></div></div><div class="off" v-if="!focus"><span class="image" :style="{'background-image': 'url(' + item.thumbnail_url + ')'}"></span><div class="info company"><div class="name">${ item.name }</div></div></div></a></div></script><script id="incremental-result-item-store" type="text/x-template"><div class="list store" :class="{'focus': focus}"><a :href="url" class="clearfix"><div class="on" v-if="focus"><span class="image" :style="{'background-image': 'url(' + item.image_url + ')'}"></span><div class="info store"></div></div><div class="off" v-if="!focus"><span class="image" :style="{'background-image': 'url(' + item.thumbnail_url + ')'}"></span><div class="info store"></div></div></a></div></script><script id="incremental-result-item-club" type="text/x-template"><div class="list club" :class="{'focus': focus}"><a :href="url" class="clearfix"><div class="on" v-if="focus"><span class="image" :style="{'background-image': 'url(' + item.image_url + ')'}"></span><div class="info club"><div class="name">${ item.name }</div><div class="extra-info">Members: ${ item.payload.members }<br>Category: ${ item.payload.category }<br>Created by: ${ item.payload.created_by }</div></div></div><div class="off" v-if="!focus"><span class="image" :style="{'background-image': 'url(' + item.thumbnail_url + ')'}"></span><div class="info club"><div class="name">${ item.name }</div></div></div></a></div></script><script id="incremental-result-item-user" type="text/x-template"><div class="list user" :class="{'focus': focus}"><a :href="url" class="clearfix"><div class="on" v-if="focus"><span class="image" :style="{'background-image': 'url(' + item.image_url + ')'}"></span><div class="info user"><div class="name">${ item.name }</div><div class="extra-info"><span v-if="item.payload.authority">${ item.payload.authority }<br></span>Joined: ${ item.payload.joined }</div></div></div><div class="off" v-if="!focus"><span class="image" :style="{'background-image': 'url(' + item.thumbnail_url + ')'}"></span><div class="info user"><div class="name">${ item.name }</div></div></div></a></div></script><script id="incremental-result-item-news" type="text/x-template"><div class="list news" :class="{'focus': focus}"><a :href="url" class="clearfix"><div class="on" v-if="focus"><span class="image" :style="{'background-image': 'url(' + item.image_url + ')'}"></span><div class="info news"><div class="name">${ item.name }</div><div class="extra-info">${ item.payload.date }</div></div></div><div class="off" v-if="!focus"><span class="image" :style="{'background-image': 'url(' + item.thumbnail_url + ')'}"></span><div class="info news"><div class="name">${ item.name }</div><div class="media-type">${ item.payload.date }</div></div></div></a></div></script><script id="incremental-result-item-featured" type="text/x-template"><div class="list featured" :class="{'focus': focus}"><a :href="url" class="clearfix"><div class="on" v-if="focus"><span class="image" :style="{'background-image': 'url(' + item.image_url + ')'}"></span><div class="info featured"><div class="name">${ item.name }</div><div class="extra-info">${ item.payload.date }</div></div></div><div class="off" v-if="!focus"><span class="image" :style="{'background-image': 'url(' + item.thumbnail_url + ')'}"></span><div class="info featured"><div class="name">${ item.name }</div><div class="media-type">${ item.payload.date }</div></div></div></a></div></script><script id="incremental-result-item-forum" type="text/x-template"><div class="list forum" :class="{'focus': focus}"><a :href="url" class="clearfix"><div class="on" v-if="focus"><span class="image" :style="{'background-image': 'url(' + item.image_url + ')'}"></span><div class="info forum"><div class="name"><span v-show="item.payload.work_title">${ item.payload.work_title}
                      <i class="fa-solid fa-caret-right"></i></span> ${ item.name }</div><div class="extra-info">${ item.payload.date }<br><span>in ${ item.payload.category }</span></div></div></div><div class="off" v-if="!focus"><span class="image" :style="{'background-image': 'url(' + item.thumbnail_url + ')'}"></span><div class="info forum"><div class="name"><span v-show="item.payload.work_title">${ item.payload.work_title}
                      <i class="fa-solid fa-caret-right"></i></span> ${ item.name }</div><div class="media-type">${ item.payload.date }</div></div></div></a></div></script><script id="incremental-result-item-separator" type="text/x-template"><div class="list separator"><div class="separator"><span v-show="item.name == 'anime'">Anime</span><span v-show="item.name == 'manga'">Manga</span><span v-show="item.name == 'character'">Characters</span><span v-show="item.name == 'person'">People</span><span v-show="item.name == 'company'">Companies</span></div></div></script><div class="js-color-pc-constant" id="top-search-bar"><form @submit.prevent="jump()" class="searchBar" id="searchBar" method="get"><div class="form-select-outer fl-l"><select class="inputtext" id="topSearchValue" name="type" v-model="type"><option value="all">All</option><option value="anime">Anime</option><option value="manga">Manga</option><option value="character">Characters</option><option value="person">People</option><option value="company">Companies</option><option value="store">Manga Store</option><option value="news">News</option><option value="featured">Featured Articles</option><option value="forum">Forum</option><option value="club">Clubs</option><option value="user">Users</option></select></div><input @blur="isFocused = false" @focus="isFocused = true" @keydown.down.prevent="moveSelection(1)" @keydown.up.prevent="moveSelection(-1)" autocomplete="off" class="inputtext fl-l" id="topSearchText" name="topkeyword" placeholder="Search Anime, Manga, and more..." size="30" type="search" v-model="keyword"/><button :class="{'notActive': (keyword.length &lt; 3)}" class="fl-l" id="topSearchButon" type="submit"><i class="fa-solid fa-magnifying-glass"></i></button></form><div :style="{display: (showResult ? 'block' : 'none')}" @mousedown.prevent="" class="incrementalSearchResultList" id="topSearchResultList"><div @mouseover="selection=i" v-for="(item, i) in items"><component :focus="selection == i" :is="resolveComponent(item)" :item="item" :url="generateItemPageUrl(item)"></component></div><div :class="{'focus': selection == -1}" :style="{display: (showViewAllLink ? 'block' : 'none')}" @mouseover="selection = -1" class="list list-bottom"><a :href="resultPageUrl">
              View all results for <span class="fw-b">${ keyword }</span><i class="fa-solid fa-spinner fa-spin ml4" v-show="isRequesting"></i></a></div></div></div></div><div id="menu_left">
<ul class="js-color-pc-constant" id="nav">
<li class="small"><a class="non-link" href="#">Anime</a><ul class="x2-wider">
<li><a href="https://myanimelist.net/anime.php?_location=mal_h_m">Anime Search</a></li>
<li><a href="https://myanimelist.net/topanime.php?_location=mal_h_m">Top Anime</a></li>
<li><a href="https://myanimelist.net/anime/season?_location=mal_h_m">Seasonal Anime</a></li>
<li><a href="https://myanimelist.net/watch/episode?_location=mal_h_m_a">Videos</a></li>
<li><a href="https://myanimelist.net/reviews.php?t=anime&amp;_location=mal_h_m">Reviews</a></li>
<li><a href="https://myanimelist.net/recommendations.php?s=recentrecs&amp;t=anime&amp;_location=mal_h_m">Recommendations</a></li>
<li><a href="https://myanimelist.net/forum?topicid=2196122&amp;_location=mal_h_m">2025 Challenge</a></li><li><a class="menu-fal-fall-icon" href="https://fal.myanimelist.net/fall_2025?utm_source=MAL&amp;utm_medium=headermenu_falfall2025&amp;utm_content=announce&amp;_location=mal_h_m">Fantasy Anime League</a></li></ul>
</li>
<li class="small"><a class="non-link" href="#">Manga</a>
<ul class="x-wider">
<li><a href="https://myanimelist.net/manga.php?_location=mal_h_m">Manga Search</a></li>
<li><a href="https://myanimelist.net/topmanga.php?_location=mal_h_m">Top Manga</a></li>
<li><a class="menu-new" href="https://myanimelist.net/manga/adapted?_location=mal_h_m">Adapted to Anime</a></li>
<li><a href="https://myanimelist.net/store?_location=mal_h_m">Manga Store</a></li>
<li><a href="https://myanimelist.net/reviews.php?t=manga&amp;_location=mal_h_m">Reviews</a></li>
<li><a href="https://myanimelist.net/recommendations.php?s=recentrecs&amp;t=manga&amp;_location=mal_h_m">Recommendations</a></li>
<li><a href="https://myanimelist.net/forum?topicid=2205133&amp;_location=mal_h_m">2025 Challenge</a></li>
</ul>
</li>
<li><a class="non-link" href="#">Community</a>
<ul>
<li><a href="https://myanimelist.net/stacks?_location=mal_h_m">Interest Stacks</a></li>
<li><a href="https://myanimelist.net/forum/?_location=mal_h_m">Forums</a></li>
<li><a href="https://myanimelist.net/clubs.php?_location=mal_h_m">Clubs</a></li>
<li><a href="https://myanimelist.net/blog.php?_location=mal_h_m">Blogs</a></li>
<li><a href="https://myanimelist.net/users.php?_location=mal_h_m">Users</a></li>
</ul>
</li>
<li class="small2"><a class="non-link" href="#">Industry</a>
<ul class="wider">
<li><a href="https://myanimelist.net/news?_location=mal_h_m">News</a></li>
<li><a href="https://myanimelist.net/featured?_location=mal_h_m">Featured Articles</a></li>
<li><a href="https://myanimelist.net/people.php?_location=mal_h_m">People</a></li>

In [ ]:
animes1 = soup.find_all("div", class_= "detail")
len(animes1)

50

In [50]:
animes1[0]

<div class="detail"><div id="area52991">
<div class="hoverinfo" id="info52991" rel="a52991"></div>
</div>
<div class="di-ib clearfix"><h3 class="fl-l fs14 fw-b anime_ranking_h3"><a class="hoverinfo_trigger" href="https://myanimelist.net/anime/52991/Sousou_no_Frieren" id="#area52991" rel="#info52991">Sousou no Frieren</a></h3><div class="icon-watch2"><a class="mal-icon ml8 ga-click" href="https://myanimelist.net/anime/52991/Sousou_no_Frieren/video" title="Watch Episode Video"><i class="malicon malicon-movie-episode"></i></a></div></div><br/><div class="information di-ib mt4">
        TV (28 eps)<br/>
        Sep 2023 - Mar 2024<br/>
        1,238,241 members
      </div> </div>

## Vamos a encontrar el titulo de un anime. Para ello:

In [37]:
animes1[0].find('h3', class_='anime_ranking_h3')

In [39]:
titulo = animes1[0].a.text.strip()
titulo

'Sousou no Frieren'

## Ahora vamos con el año de estreno:

In [ ]:
#Año de estreno:
info_block = soup.find('div', class_='information')

# Obtenemos el texto limpio
info_text = info_block.get_text(separator='\n').strip()

# Dividimos en líneas no vacías
info_lines = [line.strip() for line in info_text.split('\n') if line.strip()]



# Extraer el primer año
year = re.search(r'\b(19|20)\d{2}\b', fecha_linea).group(0) if fecha_linea else None
year

'2023'

## Y ahora con la valoración, que se encuentra en otro objeto:

In [ ]:
#Rating
ratings = soup.find_all("span", class_=re.compile(r"score-label"))

#Pero al parecer hay valoraciones ocultas que nos aparecen como N/A, por lo que necesitamos filtrarlas
ratings_validos = [r.text.strip() for r in ratingsif re.match(r'^\d+(\.\d+)?$', r.text.strip())]
for r in ratings_validos:print(r)
df_ratings = pd.DataFrame(ratings_validos, columns=['rating'])

8.50
8.50
8.50
8.50
8.50
8.49
8.49
8.49
8.48
8.48
8.48
8.48
8.47
8.47
8.47
8.47
8.47
8.47
8.46
8.46
8.46
8.46
8.46
8.46
8.46
8.45
8.45
8.45
8.45
8.45
8.45
8.44
8.44
8.44
8.44
8.44
8.44
8.43
8.43
8.43
8.43
8.42
8.42
8.42
8.42
8.42
8.42
8.42
8.42
8.42

## Todo junto quedaría así:

In [ ]:
# ---- Extraer títulos y años ----
details = soup.find_all('div', class_='detail')

titulos = []
anios = []
for detail in details:
    # ---- Título ----
    titulo_tag = detail.find('h3', class_='anime_ranking_h3')
    titulo = titulo_tag.a.text.strip() if titulo_tag and titulo_tag.a else None

    # ---- Año ----
    info_block = detail.find('div', class_='information')
    anio = None
    if info_block:
        info_text = info_block.get_text(separator='\n').strip()
        match = re.search(r'\b(19|20)\d{2}\b', info_text)
        if match:
            anio = match.group(0)

    titulos.append(titulo)
    anios.append(anio)

# ---- Extraer todos los ratings válidos ----
ratings = soup.find_all("span", class_=re.compile(r"score-label"))
ratings_validos = [r.text.strip()for r in ratings if re.match(r'^\d+(\.\d+)?$', r.text.strip())]

# ---- Emparejar todo ----
animes = []
for titulo, anio, rating in zip(titulos, anios, ratings_validos):
    animes.append({'titulo': titulo,'año': anio,'rating': rating})

# ---- Mostrar resultado ----
for a in animes:
    print(a)

{'titulo': 'Sousou no Frieren', 'año': '2023', 'rating': '9.29'}
{'titulo': 'Fullmetal Alchemist: Brotherhood', 'año': '2009', 'rating': '9.10'}
{'titulo': 'Steins;Gate', 'año': '2011', 'rating': '9.07'}
{'titulo': 'Shingeki no Kyojin Season 3 Part 2', 'año': '2019', 'rating': '9.05'}
{'titulo': 'Gintama: The Final', 'año': '2021', 'rating': '9.05'}
{'titulo': 'Gintama°', 'año': '2015', 'rating': '9.05'}
{'titulo': 'Hunter x Hunter (2011)', 'año': '2011', 'rating': '9.03'}
{'titulo': 'One Piece Fan Letter', 'año': '2024', 'rating': '9.03'}
{'titulo': 'Chainsaw Man Movie: Reze-hen', 'año': '2025', 'rating': '9.02'}
{'titulo': 'Ginga Eiyuu Densetsu', 'año': '1988', 'rating': '9.02'}
{'titulo': "Gintama'", 'año': '2011', 'rating': '9.02'}
{'titulo': "Gintama': Enchousen", 'año': '2012', 'rating': '9.02'}
{'titulo': 'Bleach: Sennen Kessen-hen', 'año': '2022', 'rating': '8.99'}
{'titulo': 'Gintama.', 'año': '2017', 'rating': '8.98'}
{'titulo': 'Kaguya-sama wa Kokurasetai: Ultra Romantic', 'año': '2022', 'rating': '8.97'}
{'titulo': 'Fruits Basket: The Final', 'año': '2021', 'rating': '8.94'}
{'titulo': 'Clannad: After Story', 'año': '2008', 'rating': '8.93'}
{'titulo': 'Gintama', 'año': '2006', 'rating': '8.93'}
{'titulo': 'Koe no Katachi', 'año': '2016', 'rating': '8.93'}
{'titulo': 'Kusuriya no Hitorigoto 2nd Season', 'año': '2025', 'rating': '8.91'}
{'titulo': 'Code Geass: Hangyaku no Lelouch R2', 'año': '2008', 'rating': '8.91'}
{'titulo': '3-gatsu no Lion 2nd Season', 'año': '2017', 'rating': '8.90'}
{'titulo': 'Gintama Movie 2: Kanketsu-hen - Yorozuya yo Eien Nare', 'año': '2013', 'rating': '8.90'}
{'titulo': 'Monster', 'año': '2004', 'rating': '8.89'}
{'titulo': 'Gintama. Shirogane no Tamashii-hen - Kouhan-sen', 'año': '2018', 'rating': '8.88'}
{'titulo': 'Kingdom 6th Season', 'año': '2025', 'rating': '8.87'}
{'titulo': 'Kusuriya no Hitorigoto', 'año': '2023', 'rating': '8.86'}
{'titulo': 'Owarimonogatari 2nd Season', 'año': '2017', 'rating': '8.86'}
{'titulo': 'Shingeki no Kyojin: The Final Season - Kanketsu-hen', 'año': '2023', 'rating': '8.86'}
{'titulo': 'Violet Evergarden Movie', 'año': '2020', 'rating': '8.84'}
{'titulo': 'Shingeki no Kyojin Movie: Kanketsu-hen - The Last Attack', 'año': '2024', 'rating': '8.83'}
{'titulo': 'Kimi no Na wa.', 'año': '2016', 'rating': '8.83'}
{'titulo': 'Kingdom 3rd Season', 'año': '2020', 'rating': '8.83'}
{'titulo': 'Vinland Saga Season 2', 'año': '2023', 'rating': '8.82'}
{'titulo': 'Takopii no Genzai', 'año': '2025', 'rating': '8.81'}
{'titulo': 'Gintama. Shirogane no Tamashii-hen', 'año': '2018', 'rating': '8.81'}
{'titulo': 'Hajime no Ippo', 'año': '2000', 'rating': '8.78'}
{'titulo': 'Shingeki no Kyojin: The Final Season', 'año': '2020', 'rating': '8.78'}
{'titulo': 'Kizumonogatari III: Reiketsu-hen', 'año': '2017', 'rating': '8.78'}
{'titulo': 'Mob Psycho 100 II', 'año': '2019', 'rating': '8.78'}
{'titulo': 'Ashita no Joe 2', 'año': '1980', 'rating': '8.77'}
{'titulo': 'Haikyuu!! Karasuno Koukou vs. Shiratorizawa Gakuen Koukou', 'año': '2016', 'rating': '8.77'}
{'titulo': 'Sen to Chihiro no Kamikakushi', 'año': '2001', 'rating': '8.77'}
{'titulo': 'Shingeki no Kyojin: The Final Season Part 2', 'año': '2022', 'rating': '8.77'}
{'titulo': 'Vinland Saga', 'año': '2019', 'rating': '8.77'}
{'titulo': 'Monogatari Series: Second Season', 'año': '2013', 'rating': '8.76'}
{'titulo': 'Cowboy Bebop', 'año': '1998', 'rating': '8.75'}
{'titulo': 'Bocchi the Rock!', 'año': '2022', 'rating': '8.74'}
{'titulo': 'Tu Bian Yingxiong X', 'año': '2025', 'rating': '8.73'}
{'titulo': 'Jujutsu Kaisen 2nd Season', 'año': '2023', 'rating': '8.73'}

## Por último, conseguir el género y repetir todo el proceso para los 200 primeros animes

In [79]:
for anime in animes1:
    print(anime)

<div class="detail"><div id="area52991">
<div class="hoverinfo" id="info52991" rel="a52991"></div>
</div>
<div class="di-ib clearfix"><h3 class="fl-l fs14 fw-b anime_ranking_h3"><a class="hoverinfo_trigger" href="https://myanimelist.net/anime/52991/Sousou_no_Frieren" id="#area52991" rel="#info52991">Sousou no Frieren</a></h3><div class="icon-watch2"><a class="mal-icon ml8 ga-click" href="https://myanimelist.net/anime/52991/Sousou_no_Frieren/video" title="Watch Episode Video"><i class="malicon malicon-movie-episode"></i></a></div></div><br/><div class="information di-ib mt4">
        TV (28 eps)<br/>
        Sep 2023 - Mar 2024<br/>
        1,238,241 members
      </div> </div>
<div class="detail"><div id="area5114">
<div class="hoverinfo" id="info5114" rel="a5114"></div>
</div>
<div class="di-ib clearfix"><h3 class="fl-l fs14 fw-b anime_ranking_h3"><a class="hoverinfo_trigger" href="https://myanimelist.net/anime/5114/Fullmetal_Alchemist__Brotherhood" id="#area5114" rel="#info5114">Fullmetal Alchemist: Brotherhood</a></h3><div class="icon-watch2"><a class="mal-icon ml8 ga-click" href="https://myanimelist.net/anime/5114/Fullmetal_Alchemist__Brotherhood/video" title="Watch Episode Video"><i class="malicon malicon-movie-episode"></i></a></div></div><br/><div class="information di-ib mt4">
        TV (64 eps)<br/>
        Apr 2009 - Jul 2010<br/>
        3,584,936 members
      </div><div class="manga-store-information ga-impression" data-ga-impression-param="aid:5114" data-ga-impression-type="buy_manga_store_anime_ranking">
<a class="link ga-click" data-ga-click-param="aid:5114" data-ga-click-type="buy_manga_store_anime_ranking" href="https://myanimelist.net/store/manga_volume/2148/Fullmetal_Alchemist_Volume_1">
<i aria-hidden="true" class="fa-solid fa-cart-shopping"></i> <span class="fw-b">Manga Store</span>
<span class="volume">Volume 1</span>
<span class="price">€4.58</span> </a><a class="button-preview ga-click" data-ga-click-param="aid:5114" data-ga-click-type="buy_manga_store_anime_ranking_preview" href="https://myanimelist.net/store/viewer/1/2148/preview" target="_blank">Preview</a></div> </div>
<div class="detail"><div id="area9253">
<div class="hoverinfo" id="info9253" rel="a9253"></div>
</div>
<div class="di-ib clearfix"><h3 class="fl-l fs14 fw-b anime_ranking_h3"><a class="hoverinfo_trigger" href="https://myanimelist.net/anime/9253/Steins_Gate" id="#area9253" rel="#info9253">Steins;Gate</a></h3><div class="icon-watch2"><a class="mal-icon ml8 ga-click" href="https://myanimelist.net/anime/9253/Steins_Gate/video" title="Watch Episode Video"><i class="malicon malicon-movie-episode"></i></a></div></div><br/><div class="information di-ib mt4">
        TV (24 eps)<br/>
        Apr 2011 - Sep 2011<br/>
        2,743,141 members
      </div> </div>
<div class="detail"><div id="area38524">
<div class="hoverinfo" id="info38524" rel="a38524"></div>
</div>
<div class="di-ib clearfix"><h3 class="fl-l fs14 fw-b anime_ranking_h3"><a class="hoverinfo_trigger" href="https://myanimelist.net/anime/38524/Shingeki_no_Kyojin_Season_3_Part_2" id="#area38524" rel="#info38524">Shingeki no Kyojin Season 3 Part 2</a></h3><div class="icon-watch2"><a class="mal-icon ml8 ga-click" href="https://myanimelist.net/anime/38524/Shingeki_no_Kyojin_Season_3_Part_2/video" title="Watch Episode Video"><i class="malicon malicon-movie-episode"></i></a></div></div><br/><div class="information di-ib mt4">
        TV (10 eps)<br/>
        Apr 2019 - Jul 2019<br/>
        2,504,377 members
      </div><div class="manga-store-information ga-impression" data-ga-impression-param="aid:38524" data-ga-impression-type="buy_manga_store_anime_ranking">
<a class="link ga-click" data-ga-click-param="aid:38524" data-ga-click-type="buy_manga_store_anime_ranking" href="https://myanimelist.net/store/manga_volume/394/Attack_on_Titan_Volume_1">
<i aria-hidden="true" class="fa-solid fa-cart-shopping"></i> <span class="fw-b">Manga Store</span>
<span class="volume">Volume 1</span>
<span class="price">€10.99</span> </a><a class="button-preview ga-click" data-ga-click-param="aid:38524" data-ga-click-type="buy_manga_store_anime_ranking_preview" href="https://myanimelist.net/store/viewer/1/394/preview" target="_blank">Preview</a></div> </div>
<div class="detail"><div id="area39486">
<div class="hoverinfo" id="info39486" rel="a39486"></div>
</div>
<div class="di-ib clearfix"><h3 class="fl-l fs14 fw-b anime_ranking_h3"><a class="hoverinfo_trigger" href="https://myanimelist.net/anime/39486/Gintama__The_Final" id="#area39486" rel="#info39486">Gintama: The Final</a></h3><div class="icon-watch2"><a class="mal-icon ml8 ga-click" href="https://myanimelist.net/anime/39486/Gintama__The_Final/video" title="Watch Episode Video"><i class="malicon malicon-movie-episode"></i></a></div></div><br/><div class="information di-ib mt4">
        Movie (1 eps)<br/>
        Jan 2021 - Jan 2021<br/>
        175,524 members
      </div> </div>
<div class="detail"><div id="area28977">
<div class="hoverinfo" id="info28977" rel="a28977"></div>
</div>
<div class="di-ib clearfix"><h3 class="fl-l fs14 fw-b anime_ranking_h3"><a class="hoverinfo_trigger" href="https://myanimelist.net/anime/28977/Gintama°" id="#area28977" rel="#info28977">Gintama°</a></h3><div class="icon-watch2"><a class="mal-icon ml8 ga-click" href="https://myanimelist.net/anime/28977/Gintama%C2%B0/video" title="Watch Episode Video"><i class="malicon malicon-movie-episode"></i></a></div></div><br/><div class="information di-ib mt4">
        TV (51 eps)<br/>
        Apr 2015 - Mar 2016<br/>
        677,470 members
      </div> </div>
<div class="detail"><div id="area11061">
<div class="hoverinfo" id="info11061" rel="a11061"></div>
</div>
<div class="di-ib clearfix"><h3 class="fl-l fs14 fw-b anime_ranking_h3"><a class="hoverinfo_trigger" href="https://myanimelist.net/anime/11061/Hunter_x_Hunter_2011" id="#area11061" rel="#info11061">Hunter x Hunter (2011)</a></h3><div class="icon-watch2"><a class="mal-icon ml8 ga-click" href="https://myanimelist.net/anime/11061/Hunter_x_Hunter_2011/video" title="Watch Episode Video"><i class="malicon malicon-movie-episode"></i></a></div></div><br/><div class="information di-ib mt4">
        TV (148 eps)<br/>
        Oct 2011 - Sep 2014<br/>
        3,089,733 members
      </div> </div>
<div class="detail"><div id="area60022">
<div class="hoverinfo" id="info60022" rel="a60022"></div>
</div>
<div class="di-ib clearfix"><h3 class="fl-l fs14 fw-b anime_ranking_h3"><a class="hoverinfo_trigger" href="https://myanimelist.net/anime/60022/One_Piece_Fan_Letter" id="#area60022" rel="#info60022">One Piece Fan Letter</a></h3><div class="icon-watch-pv2"><a class="mal-icon ml8 ga-click" href="https://myanimelist.net/anime/60022/One_Piece_Fan_Letter/video" title="Watch Promotional Video"><i class="malicon malicon-movie-pv"></i></a></div></div><br/><div class="information di-ib mt4">
        TV Special (1 eps)<br/>
        Oct 2024 - Oct 2024<br/>
        130,129 members
      </div> </div>
<div class="detail"><div id="area57555">
<div class="hoverinfo" id="info57555" rel="a57555"></div>
</div>
<div class="di-ib clearfix"><h3 class="fl-l fs14 fw-b anime_ranking_h3"><a class="hoverinfo_trigger" href="https://myanimelist.net/anime/57555/Chainsaw_Man_Movie__Reze-hen" id="#area57555" rel="#info57555">Chainsaw Man Movie: Reze-hen</a></h3><div class="icon-watch-pv2"><a class="mal-icon ml8 ga-click" href="https://myanimelist.net/anime/57555/Chainsaw_Man_Movie__Reze-hen/video" title="Watch Promotional Video"><i class="malicon malicon-movie-pv"></i></a></div></div><br/><div class="information di-ib mt4">
        Movie (1 eps)<br/>
        Sep 2025 - Sep 2025<br/>
        170,923 members
      </div> </div>
<div class="detail"><div id="area820">
<div class="hoverinfo" id="info820" rel="a820"></div>
</div>
<div class="di-ib clearfix"><h3 class="fl-l fs14 fw-b anime_ranking_h3"><a class="hoverinfo_trigger" href="https://myanimelist.net/anime/820/Ginga_Eiyuu_Densetsu" id="#area820" rel="#info820">Ginga Eiyuu Densetsu</a></h3><div class="icon-watch-pv2"><a class="mal-icon ml8 ga-click" href="https://myanimelist.net/anime/820/Ginga_Eiyuu_Densetsu/video" title="Watch Promotional Video"><i class="malicon malicon-movie-pv"></i></a></div></div><br/><div class="information di-ib mt4">
        OVA (110 eps)<br/>
        Jan 1988 - Mar 1997<br/>
        351,656 members
      </div> </div>
<div class="detail"><div id="area9969">
<div class="hoverinfo" id="info9969" rel="a9969"></div>
</div>
<div class="di-ib clearfix"><h3 class="fl-l fs14 fw-b anime_ranking_h3"><a class="hoverinfo_trigger" href="https://myanimelist.net/anime/9969/Gintama" id="#area9969" rel="#info9969">Gintama'</a></h3><div class="icon-watch2"><a class="mal-icon ml8 ga-click" href="https://myanimelist.net/anime/9969/Gintama/video" title="Watch Episode Video"><i class="malicon malicon-movie-episode"></i></a></div></div><br/><div class="information di-ib mt4">
        TV (51 eps)<br/>
        Apr 2011 - Mar 2012<br/>
        599,496 members
      </div> </div>
<div class="detail"><div id="area15417">
<div class="hoverinfo" id="info15417" rel="a15417"></div>
</div>
<div class="di-ib clearfix"><h3 class="fl-l fs14 fw-b anime_ranking_h3"><a class="hoverinfo_trigger" href="https://myanimelist.net/anime/15417/Gintama__Enchousen" id="#area15417" rel="#info15417">Gintama': Enchousen</a></h3><div class="icon-watch2"><a class="mal-icon ml8 ga-click" href="https://myanimelist.net/anime/15417/Gintama__Enchousen/video" title="Watch Episode Video"><i class="malicon malicon-movie-episode"></i></a></div></div><br/><div class="information di-ib mt4">
        TV (13 eps)<br/>
        Oct 2012 - Mar 2013<br/>
        350,715 members
      </div> </div>
<div class="detail"><div id="area41467">
<div class="hoverinfo" id="info41467" rel="a41467"></div>
</div>
<div class="di-ib clearfix"><h3 class="fl-l fs14 fw-b anime_ranking_h3"><a class="hoverinfo_trigger" href="https://myanimelist.net/anime/41467/Bleach__Sennen_Kessen-hen" id="#area41467" rel="#info41467">Bleach: Sennen Kessen-hen</a></h3><div class="icon-watch-pv2"><a class="mal-icon ml8 ga-click" href="https://myanimelist.net/anime/41467/Bleach__Sennen_Kessen-hen/video" title="Watch Promotional Video"><i class="malicon malicon-movie-pv"></i></a></div></div><br/><div class="information di-ib mt4">
        TV (13 eps)<br/>
        Oct 2022 - Dec 2022<br/>
        663,935 members
      </div> </div>
<div class="detail"><div id="area34096">
<div class="hoverinfo" id="info34096" rel="a34096"></div>
</div>
<div class="di-ib clearfix"><h3 class="fl-l fs14 fw-b anime_ranking_h3"><a class="hoverinfo_trigger" href="https://myanimelist.net/anime/34096/Gintama" id="#area34096" rel="#info34096">Gintama.</a></h3><div class="icon-watch2"><a class="mal-icon ml8 ga-click" href="https://myanimelist.net/anime/34096/Gintama/video" title="Watch Episode Video"><i class="malicon malicon-movie-episode"></i></a></div></div><br/><div class="information di-ib mt4">
        TV (12 eps)<br/>
        Jan 2017 - Mar 2017<br/>
        340,727 members
      </div> </div>
<div class="detail"><div id="area43608">
<div class="hoverinfo" id="info43608" rel="a43608"></div>
</div>
<div class="di-ib clearfix"><h3 class="fl-l fs14 fw-b anime_ranking_h3"><a class="hoverinfo_trigger" href="https://myanimelist.net/anime/43608/Kaguya-sama_wa_Kokurasetai__Ultra_Romantic" id="#area43608" rel="#info43608">Kaguya-sama wa Kokurasetai: Ultra Romantic</a></h3><div class="icon-watch2"><a class="mal-icon ml8 ga-click" href="https://myanimelist.net/anime/43608/Kaguya-sama_wa_Kokurasetai__Ultra_Romantic/video" title="Watch Episode Video"><i class="malicon malicon-movie-episode"></i></a></div></div><br/><div class="information di-ib mt4">
        TV (13 eps)<br/>
        Apr 2022 - Jun 2022<br/>
        1,062,868 members
      </div> </div>
<div class="detail"><div id="area42938">
<div class="hoverinfo" id="info42938" rel="a42938"></div>
</div>
<div class="di-ib clearfix"><h3 class="fl-l fs14 fw-b anime_ranking_h3"><a class="hoverinfo_trigger" href="https://myanimelist.net/anime/42938/Fruits_Basket__The_Final" id="#area42938" rel="#info42938">Fruits Basket: The Final</a></h3><div class="icon-watch2"><a class="mal-icon ml8 ga-click" href="https://myanimelist.net/anime/42938/Fruits_Basket__The_Final/video" title="Watch Episode Video"><i class="malicon malicon-movie-episode"></i></a></div></div><br/><div class="information di-ib mt4">
        TV (13 eps)<br/>
        Apr 2021 - Jun 2021<br/>
        543,187 members
      </div><div class="manga-store-information ga-impression" data-ga-impression-param="aid:42938" data-ga-impression-type="buy_manga_store_anime_ranking">
<a class="link ga-click" data-ga-click-param="aid:42938" data-ga-click-type="buy_manga_store_anime_ranking" href="https://myanimelist.net/store/manga_volume/4551/Fruits_Basket_Collectors_Edition_Volume_1">
<i aria-hidden="true" class="fa-solid fa-cart-shopping"></i> <span class="fw-b">Manga Store</span>
<span class="volume">Volume 1</span>
<span class="price">€6.66</span> </a><a class="button-preview ga-click" data-ga-click-param="aid:42938" data-ga-click-type="buy_manga_store_anime_ranking_preview" href="https://myanimelist.net/store/viewer/1/4551/preview" target="_blank">Preview</a></div> </div>
<div class="detail"><div id="area4181">
<div class="hoverinfo" id="info4181" rel="a4181"></div>
</div>
<div class="di-ib clearfix"><h3 class="fl-l fs14 fw-b anime_ranking_h3"><a class="hoverinfo_trigger" href="https://myanimelist.net/anime/4181/Clannad__After_Story" id="#area4181" rel="#info4181">Clannad: After Story</a></h3><div class="icon-watch2"><a class="mal-icon ml8 ga-click" href="https://myanimelist.net/anime/4181/Clannad__After_Story/video" title="Watch Episode Video"><i class="malicon malicon-movie-episode"></i></a></div></div><br/><div class="information di-ib mt4">
        TV (24 eps)<br/>
        Oct 2008 - Mar 2009<br/>
        1,260,779 members
      </div> </div>
<div class="detail"><div id="area918">
<div class="hoverinfo" id="info918" rel="a918"></div>
</div>
<div class="di-ib clearfix"><h3 class="fl-l fs14 fw-b anime_ranking_h3"><a class="hoverinfo_trigger" href="https://myanimelist.net/anime/918/Gintama" id="#area918" rel="#info918">Gintama</a></h3><div class="icon-watch2"><a class="mal-icon ml8 ga-click" href="https://myanimelist.net/anime/918/Gintama/video" title="Watch Episode Video"><i class="malicon malicon-movie-episode"></i></a></div></div><br/><div class="information di-ib mt4">
        TV (201 eps)<br/>
        Apr 2006 - Mar 2010<br/>
        1,131,522 members
      </div> </div>
<div class="detail"><div id="area28851">
<div class="hoverinfo" id="info28851" rel="a28851"></div>
</div>
<div class="di-ib clearfix"><h3 class="fl-l fs14 fw-b anime_ranking_h3"><a class="hoverinfo_trigger" href="https://myanimelist.net/anime/28851/Koe_no_Katachi" id="#area28851" rel="#info28851">Koe no Katachi</a></h3><div class="icon-watch-pv2"><a class="mal-icon ml8 ga-click" href="https://myanimelist.net/anime/28851/Koe_no_Katachi/video" title="Watch Promotional Video"><i class="malicon malicon-movie-pv"></i></a></div></div><br/><div class="information di-ib mt4">
        Movie (1 eps)<br/>
        Sep 2016 - Sep 2016<br/>
        2,532,828 members
      </div><div class="manga-store-information ga-impression" data-ga-impression-param="aid:28851" data-ga-impression-type="buy_manga_store_anime_ranking">
<a class="link ga-click" data-ga-click-param="aid:28851" data-ga-click-type="buy_manga_store_anime_ranking" href="https://myanimelist.net/store/manga_volume/497/A_Silent_Voice_Volume_1">
<i aria-hidden="true" class="fa-solid fa-cart-shopping"></i> <span class="fw-b">Manga Store</span>
<span class="volume">Volume 1</span>
<span class="price">€10.99</span> </a><a class="button-preview ga-click" data-ga-click-param="aid:28851" data-ga-click-type="buy_manga_store_anime_ranking_preview" href="https://myanimelist.net/store/viewer/1/497/preview" target="_blank">Preview</a></div> </div>
<div class="detail"><div id="area58514">
<div class="hoverinfo" id="info58514" rel="a58514"></div>
</div>
<div class="di-ib clearfix"><h3 class="fl-l fs14 fw-b anime_ranking_h3"><a class="hoverinfo_trigger" href="https://myanimelist.net/anime/58514/Kusuriya_no_Hitorigoto_2nd_Season" id="#area58514" rel="#info58514">Kusuriya no Hitorigoto 2nd Season</a></h3><div class="icon-watch2"><a class="mal-icon ml8 ga-click" href="https://myanimelist.net/anime/58514/Kusuriya_no_Hitorigoto_2nd_Season/video" title="Watch Episode Video"><i class="malicon malicon-movie-episode"></i></a></div></div><br/><div class="information di-ib mt4">
        TV (24 eps)<br/>
        Jan 2025 - Jul 2025<br/>
        410,644 members
      </div> </div>
<div class="detail"><div id="area2904">
<div class="hoverinfo" id="info2904" rel="a2904"></div>
</div>
<div class="di-ib clearfix"><h3 class="fl-l fs14 fw-b anime_ranking_h3"><a class="hoverinfo_trigger" href="https://myanimelist.net/anime/2904/Code_Geass__Hangyaku_no_Lelouch_R2" id="#area2904" rel="#info2904">Code Geass: Hangyaku no Lelouch R2</a></h3><div class="icon-watch2"><a class="mal-icon ml8 ga-click" href="https://myanimelist.net/anime/2904/Code_Geass__Hangyaku_no_Lelouch_R2/video" title="Watch Episode Video"><i class="malicon malicon-movie-episode"></i></a></div></div><br/><div class="information di-ib mt4">
        TV (25 eps)<br/>
        Apr 2008 - Sep 2008<br/>
        1,904,740 members
      </div> </div>
<div class="detail"><div id="area35180">
<div class="hoverinfo" id="info35180" rel="a35180"></div>
</div>
<div class="di-ib clearfix"><h3 class="fl-l fs14 fw-b anime_ranking_h3"><a class="hoverinfo_trigger" href="https://myanimelist.net/anime/35180/3-gatsu_no_Lion_2nd_Season" id="#area35180" rel="#info35180">3-gatsu no Lion 2nd Season</a></h3><div class="icon-watch2"><a class="mal-icon ml8 ga-click" href="https://myanimelist.net/anime/35180/3-gatsu_no_Lion_2nd_Season/video" title="Watch Episode Video"><i class="malicon malicon-movie-episode"></i></a></div></div><br/><div class="information di-ib mt4">
        TV (22 eps)<br/>
        Oct 2017 - Mar 2018<br/>
        430,023 members
      </div> </div>
<div class="detail"><div id="area15335">
<div class="hoverinfo" id="info15335" rel="a15335"></div>
</div>
<div class="di-ib clearfix"><h3 class="fl-l fs14 fw-b anime_ranking_h3"><a class="hoverinfo_trigger" href="https://myanimelist.net/anime/15335/Gintama_Movie_2__Kanketsu-hen_-_Yorozuya_yo_Eien_Nare" id="#area15335" rel="#info15335">Gintama Movie 2: Kanketsu-hen - Yorozuya yo Eien Nare</a></h3><div class="icon-watch-pv2"><a class="mal-icon ml8 ga-click" href="https://myanimelist.net/anime/15335/Gintama_Movie_2__Kanketsu-hen_-_Yorozuya_yo_Eien_Nare/video" title="Watch Promotional Video"><i class="malicon malicon-movie-pv"></i></a></div></div><br/><div class="information di-ib mt4">
        Movie (1 eps)<br/>
        Jul 2013 - Jul 2013<br/>
        257,762 members
      </div> </div>
<div class="detail"><div id="area19">
<div class="hoverinfo" id="info19" rel="a19"></div>
</div>
<div class="di-ib clearfix"><h3 class="fl-l fs14 fw-b anime_ranking_h3"><a class="hoverinfo_trigger" href="https://myanimelist.net/anime/19/Monster" id="#area19" rel="#info19">Monster</a></h3><div class="icon-watch2"><a class="mal-icon ml8 ga-click" href="https://myanimelist.net/anime/19/Monster/video" title="Watch Episode Video"><i class="malicon malicon-movie-episode"></i></a></div></div><br/><div class="information di-ib mt4">
        TV (74 eps)<br/>
        Apr 2004 - Sep 2005<br/>
        1,270,748 members
      </div> </div>
<div class="detail"><div id="area37491">
<div class="hoverinfo" id="info37491" rel="a37491"></div>
</div>

In [80]:
animes1[0].find("h3").find("a").get("href")

'https://myanimelist.net/anime/52991/Sousou_no_Frieren'

In [84]:
url2= animes1[0].find("h3").find("a").get("href")
url2

'https://myanimelist.net/anime/52991/Sousou_no_Frieren'

In [ ]:
response2 = requests.get(url2)
soup2 = BeautifulSoup(response2.content, "html.parser")
soup2

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html class="appearance-none" lang="en" xmlns:fb="http://www.facebook.com/2008/fbml" xmlns:og="http://ogp.me/ns#">
<head>
<link crossorigin="anonymous" href="//www.googletagmanager.com/" rel="preconnect"/>
<link crossorigin="anonymous" href="https://cdn.myanimelist.net" rel="preconnect"/>
<title>
Sousou no Frieren (Frieren: Beyond Journey's End) - MyAnimeList.net
</title>
<meta content="Looking for information on the anime Sousou no Frieren (Frieren: Beyond Journey's End)? Find out more with MyAnimeList, the world's most active online anime and manga community and database. During their decade-long quest to defeat the Demon King, the members of the hero's party—Himmel himself, the priest Heiter, the dwarf warrior Eisen, and the elven mage Frieren—forge bonds through adventures and battles, creating unforgettable precious memories for most of them. However, the time that Fri..." name="description"/>
<meta content="anime, myanimelist, anime news, manga" name="keywords"/>
<meta content="en_US" property="og:locale"/><meta content="360769957454434" property="fb:app_id"/><meta content="MyAnimeList.net" property="og:site_name"/><meta content="summary" name="twitter:card"/><meta content="@myanimelist" name="twitter:site"/><meta content="Sousou no Frieren" property="og:title"/><meta content="video.tv_show" property="og:type"/><meta content="https://cdn.myanimelist.net/images/anime/1015/138006.jpg" property="og:image"/><meta content="https://cdn.myanimelist.net/r/360x360/images/anime/1015/138006.jpg?s=e09141701f03a87ed832ea54c688f13d" name="twitter:image:src"/><meta content="https://myanimelist.net/anime/52991/Sousou_no_Frieren" property="og:url"/><meta content="During their decade-long quest to defeat the Demon King, the members of the hero's party—Himmel himself, the priest Heiter, the dwarf warrior Eisen, and the elven mage Frieren—forge bonds through adventures and battles, creating unforgettable precious memories for most of them. However, the time that Frieren spends with her comrades is equivalent to merely a fraction of her life, which has lasted over a thousand years. When the party disbands after their victory, Frieren casually returns to her &quot;usual&quot; routine of collecting spells across the continent. Due to her different sense of time, she seemingly holds no strong feelings toward the experiences she went through. As the years pass, Frieren gradually realizes how her days in the hero's party truly impacted her. Witnessing the deaths of two of her former companions, Frieren begins to regret having taken their presence for granted; she vows to better understand humans and create real personal connections. Although the story of that once memorable journey has long ended, a new tale is about to begin. [Written by MAL Rewrite]" property="og:description"/>
<meta content="default" name="referrer"/><link href="/manifest.json" rel="manifest"/>
<meta content="d2de886efeaded5adb814835c51551a10828fdbb" name="csrf_token"/>
<meta content="1e927243-8e02-48e3-b098-a7b78c5b4e36" name="fo-verify"/><meta content="initial-scale=1" name="viewport"><script src="https://cdn.myanimelist.net/static/viewer/js/logpose.min.js?v=20250929-8"></script>
<script defer="" src="https://cdn.myanimelist.net/static/viewer/js/logpose.global.js?v=20250929-8"></script>
<link as="style" href="https://cdn.myanimelist.net/static/assets/css/pc/style-710d81a83e.css" rel="preload">
<link as="style" href="https://cdn.myanimelist.net/static/assets/css/pc/dark-589cb567fb.css" rel="preload"/>
<link as="script" href="https://cdn.myanimelist.net/static/assets/js/pc/header-f5baf24c79.js" rel="preload"/>
<link as="script" href="https://cdn.myanimelist.net/static/assets/js/pc/all-9de2ec12ad.js" rel="preload"/>
<link href="https://cdn.myanimelist.net/static/assets/css/pc/style-710d81a83e.css" rel="stylesheet" type="text/css"/>
<link href="https://cdn.myanimelist.net/static/assets/css/pc/dark-589cb567fb.css" rel="stylesheet" type="text/css"/>
<script src="https://cdn.myanimelist.net/static/assets/js/pc/header-f5baf24c79.js" type="text/javascript"></script>
<script async="async" data-params='{"origin_url":"https:\/\/myanimelist.net"}' id="alljs" src="https://cdn.myanimelist.net/static/assets/js/pc/all-9de2ec12ad.js" type="text/javascript"></script>
<link href="https://myanimelist.net/plugins/myanimelist.xml" rel="search" title="MyAnimeList" type="application/opensearchdescription+xml"/>
<link href="https://cdn.myanimelist.net/images/favicon.ico" rel="shortcut icon" sizes="any" type="image/vnd.microsoft.icon"/>
<link href="https://cdn.myanimelist.net/images/favicon.svg" rel="icon" sizes="any" type="image/svg+xml"/>
<meta content="6Ld_1aIZAAAAAF6bNdR67ICKIaeXLKlbhE7t2Qz4" name="recaptcha_site_key"/>
<script>
window.GRECAPTCHA_SITE_KEY = '6Ld_1aIZAAAAAF6bNdR67ICKIaeXLKlbhE7t2Qz4';
</script>
<script async="" defer="" src="https://www.google.com/recaptcha/api.js?render=6Ld_1aIZAAAAAF6bNdR67ICKIaeXLKlbhE7t2Qz4"></script>
<link href="https://fonts.googleapis.com/css?family=Roboto:400,700&amp;display=swap" rel="stylesheet"/><script src="https://cdn.myanimelist.net/js/quantcast_choice.js?v=1760986998" type="text/javascript"></script>
<script src="https://cdn.myanimelist.net/js/cmp.js?v=1760986998" type="text/javascript"></script>
<script async="" src="https://btloader.com/tag?o=5110059113906176&amp;upapi=true"></script>
<!--<script src="https://hb.vntsm.com/v3/live/ad-manager.min.js" type="text/javascript" data-site-id="65a1835ac178db4aeb9540ce" data-mode="scan" async></script>-->
<script>
  var clientDarkMode = window.matchMedia("(prefers-color-scheme:dark)").matches;
  let darkMode = false

  if (clientDarkMode) {
    if (!$('html').hasClass("appearance-light")) { // SystemSetting = Dark && MAL UserSettings != Light
      darkMode = true
    }
  } else if ($('html').hasClass("appearance-dark")) { // MAL UserSettings = Dark
    darkMode = true
  }

    if (darkMode) {
    $('html').addClass("dark-mode");
  }
    $(document).ready(function() {
    if (darkMode) {
      if($('.js-color-pc-constant').length){$('.js-color-pc-constant').addClass("color-pc-constant");}
    }
  });

    window.stripeConfig = {
    disabled: false,
    maintenanceMessage: ""
  };
</script>
</link></meta></head>
<body class="page-common" data-country-code="ES" data-ms="true" data-time="1760986998" onload=" ">
<div id="myanimelist">
<script type="text/javascript">
    window.MAL.SkinAd.prepareForSkin('');
  </script>
<div class="ad-skin-side-outer ad-skin-side-bg bg-left" id="ad-skin-bg-left">
<div class="ad-skin-side left" id="ad-skin-left" style="display: none;">
<div id="ad-skin-left-absolute-block">
<div id="ad-skin-left-fixed-block"></div>
</div>
</div>
</div>
<div class="wrapper"><div class="" id="headerSmall"><a class="link-mal-logo" href="/">MyAnimeList.net</a> <script>(deployads = window.deployads || []).disablePageSegmentSessionTracking = true; </script>
<script>(deployads = window.deployads || []).pageSegment = 'anime_title_52991';</script>
<script>
    var trackOutboundLink = function(url) {
        if (typeof ga !== 'undefined') {
            ga('send', 'event', 'outbound', 'click', url, {
                'transport': 'beacon',
                'hitCallback': function(){return true;}
            });
        }
    }
</script><div class="banner-header-anime-straming header-mini-banner" style="right:480px;">
<a class="ga-click" data-ga-click-param="mini_banner_20250331_ysrtm2025_result" data-ga-click-type="mb" href="https://mxj.myanimelist.net/readthismanga/2025?utm_source=MAL&amp;utm_medium=all_TMB_readthismanga-2025-result" onclick="trackOutboundLink(''https://mxj.myanimelist.net/readthismanga/2025?utm_source=MAL&amp;utm_medium=all_TMB_readthismanga-2025-result'')"> <img alt="You Should Read This Manga" class="ga-impression" data-ga-impression-param="mini_banner_20250331_ysrtm2025_result" data-ga-impression-type="mb" height="36" src="/c/img/resources/mb/mini_banner_20250331_ysrtm2025_result.png" title="You Should Read This Manga" width="250"/> </a>
</div>
<div id="header-menu"><div class="header-menu-login"><a class="btn-mal-service ga-click ga-impression" data-ga-click-type="hide-ads" data-ga-impression-type="hide-ads" href="https://myanimelist.net/membership?_location=mal_h_u" onclick="ga_mal_banner()">Hide Ads</a><a class="btn-login" href="https://myanimelist.net/login.php?from=%2Fanime%2F52991%2FSousou_no_Frieren" id="malLogin" onclick="ga_notlogin()">Login</a><a class="btn-signup" href="https://myanimelist.net/register.php?from=%2Fanime%2F52991%2FSousou_no_Frieren" onclick="ga_registration()">Sign Up</a></div></div></div> <div class="" id="menu">
<div id="menu_right"><script id="incremental-result-item-anime" type="text/x-template"><div class="list anime" :class="{'focus': focus}"><a :href="url" class="clearfix"><div class="on" v-if="focus"><span class="image" :style="{'background-image': 'url(' + item.image_url + ')'}"></span><div class="info anime"><div class="name">${ item.name } <span class="media-type">(${ item.payload.media_type })</span></div><div class="extra-info">Aired: ${ item.payload.aired }<br>Score: ${ item.payload.score }<br>Status: ${ item.payload.status }</div></div></div><div class="off" v-if="!focus"><span class="image" :style="{'background-image': 'url(' + item.thumbnail_url + ')'}"></span><div class="info anime"><div class="name">${ item.name }</div><div class="media-type">(${ mediaTypeWithStartYear })</div></div></div></a></div></script><script id="incremental-result-item-manga" type="text/x-template"><div class="list manga" :class="{'focus': focus}"><a :href="url" class="clearfix"><div class="on" v-if="focus"><span class="image" :style="{'background-image': 'url(' + item.image_url + ')'}"></span><div class="info manga"><div class="name">${ item.name } <span class="media-type">(${ item.payload.media_type })</span></div><div class="extra-info">Published: ${ item.payload.published }<br>Score: ${ item.payload.score }<br>Status: ${ item.payload.status }</div></div></div><div class="off" v-if="!focus"><span class="image" :style="{'background-image': 'url(' + item.thumbnail_url + ')'}"></span><div class="info manga"><div class="name">${ item.name }</div><div class="media-type">(${ mediaTypeWithStartYear })</div></div></div></a></div></script><script id="incremental-result-item-character" type="text/x-template"><div class="list character" :class="{'focus': focus}"><a :href="url" class="clearfix"><div class="on" v-if="focus"><span class="image" :style="{'background-image': 'url(' + item.image_url + ')'}"></span><div class="info character"><div class="name"  v-html="item.name"></div><div class="extra-info"><ul class="related-works"><li v-for="work in item.payload.related_works" class="fs-i">- ${ work }</li></ul>Favorites: ${ item.payload.favorites }</div></div></div><div class="off" v-if="!focus"><span class="image" :style="{'background-image': 'url(' + item.thumbnail_url + ')'}"></span><div class="info character"><div class="name"  v-html="item.name"></div></div></div></a></div></script><script id="incremental-result-item-person" type="text/x-template"><div class="list person" :class="{'focus': focus}"><a :href="url" class="clearfix"><div class="on" v-if="focus"><span class="image" :style="{'background-image': 'url(' + item.image_url + ')'}"></span><div class="info person"><div class="name">${ item.name }</div><div class="extra-info"><span v-if="item.payload.alternative_name">${ item.payload.alternative_name }<br></span>Birthday: ${ item.payload.birthday }<br>Favorites: ${ item.payload.favorites }</div></div></div><div class="off" v-if="!focus"><span class="image" :style="{'background-image': 'url(' + item.thumbnail_url + ')'}"></span><div class="info person"><div class="name">${ item.name }</div></div></div></a></div></script><script id="incremental-result-item-company" type="text/x-template"><div class="list company" :class="{'focus': focus}"><a :href="url" class="clearfix"><div class="on" v-if="focus"><span class="image" :style="{'background-image': 'url(' + item.image_url + ')'}"></span><div class="info company"><div class="name">${ item.name }</div><div class="extra-info"><span v-if="item.payload.japanese">(${ item.payload.japanese })<br></span>
                        Anime titles: ${ item.payload.num_animes.toLocaleString() }<br>
                        Favorites: ${item.payload.favorites.toLocaleString()}
                    </div></div></div><div class="off" v-if="!focus"><span class="image" :style="{'background-image': 'url(' + item.thumbnail_url + ')'}"></span><div class="info company"><div class="name">${ item.name }</div></div></div></a></div></script><script id="incremental-result-item-store" type="text/x-template"><div class="list store" :class="{'focus': focus}"><a :href="url" class="clearfix"><div class="on" v-if="focus"><span class="image" :style="{'background-image': 'url(' + item.image_url + ')'}"></span><div class="info store"></div></div><div class="off" v-if="!focus"><span class="image" :style="{'background-image': 'url(' + item.thumbnail_url + ')'}"></span><div class="info store"></div></div></a></div></script><script id="incremental-result-item-club" type="text/x-template"><div class="list club" :class="{'focus': focus}"><a :href="url" class="clearfix"><div class="on" v-if="focus"><span class="image" :style="{'background-image': 'url(' + item.image_url + ')'}"></span><div class="info club"><div class="name">${ item.name }</div><div class="extra-info">Members: ${ item.payload.members }<br>Category: ${ item.payload.category }<br>Created by: ${ item.payload.created_by }</div></div></div><div class="off" v-if="!focus"><span class="image" :style="{'background-image': 'url(' + item.thumbnail_url + ')'}"></span><div class="info club"><div class="name">${ item.name }</div></div></div></a></div></script><script id="incremental-result-item-user" type="text/x-template"><div class="list user" :class="{'focus': focus}"><a :href="url" class="clearfix"><div class="on" v-if="focus"><span class="image" :style="{'background-image': 'url(' + item.image_url + ')'}"></span><div class="info user"><div class="name">${ item.name }</div><div class="extra-info"><span v-if="item.payload.authority">${ item.payload.authority }<br></span>Joined: ${ item.payload.joined }</div></div></div><div class="off" v-if="!focus"><span class="image" :style="{'background-image': 'url(' + item.thumbnail_url + ')'}"></span><div class="info user"><div class="name">${ item.name }</div></div></div></a></div></script><script id="incremental-result-item-news" type="text/x-template"><div class="list news" :class="{'focus': focus}"><a :href="url" class="clearfix"><div class="on" v-if="focus"><span class="image" :style="{'background-image': 'url(' + item.image_url + ')'}"></span><div class="info news"><div class="name">${ item.name }</div><div class="extra-info">${ item.payload.date }</div></div></div><div class="off" v-if="!focus"><span class="image" :style="{'background-image': 'url(' + item.thumbnail_url + ')'}"></span><div class="info news"><div class="name">${ item.name }</div><div class="media-type">${ item.payload.date }</div></div></div></a></div></script><script id="incremental-result-item-featured" type="text/x-template"><div class="list featured" :class="{'focus': focus}"><a :href="url" class="clearfix"><div class="on" v-if="focus"><span class="image" :style="{'background-image': 'url(' + item.image_url + ')'}"></span><div class="info featured"><div class="name">${ item.name }</div><div class="extra-info">${ item.payload.date }</div></div></div><div class="off" v-if="!focus"><span class="image" :style="{'background-image': 'url(' + item.thumbnail_url + ')'}"></span><div class="info featured"><div class="name">${ item.name }</div><div class="media-type">${ item.payload.date }</div></div></div></a></div></script><script id="incremental-result-item-forum" type="text/x-template"><div class="list forum" :class="{'focus': focus}"><a :href="url" class="clearfix"><div class="on" v-if="focus"><span class="image" :style="{'background-image': 'url(' + item.image_url + ')'}"></span><div class="info forum"><div class="name"><span v-show="item.payload.work_title">${ item.payload.work_title}
                      <i class="fa-solid fa-caret-right"></i></span> ${ item.name }</div><div class="extra-info">${ item.payload.date }<br><span>in ${ item.payload.category }</span></div></div></div><div class="off" v-if="!focus"><span class="image" :style="{'background-image': 'url(' + item.thumbnail_url + ')'}"></span><div class="info forum"><div class="name"><span v-show="item.payload.work_title">${ item.payload.work_title}
                      <i class="fa-solid fa-caret-right"></i></span> ${ item.name }</div><div class="media-type">${ item.payload.date }</div></div></div></a></div></script><script id="incremental-result-item-separator" type="text/x-template"><div class="list separator"><div class="separator"><span v-show="item.name == 'anime'">Anime</span><span v-show="item.name == 'manga'">Manga</span><span v-show="item.name == 'character'">Characters</span><span v-show="item.name == 'person'">People</span><span v-show="item.name == 'company'">Companies</span></div></div></script><div class="js-color-pc-constant" id="top-search-bar"><form @submit.prevent="jump()" class="searchBar" id="searchBar" method="get"><div class="form-select-outer fl-l"><select class="inputtext" id="topSearchValue" name="type" v-model="type"><option value="all">All</option><option value="anime">Anime</option><option value="manga">Manga</option><option value="character">Characters</option><option value="person">People</option><option value="company">Companies</option><option value="store">Manga Store</option><option value="news">News</option><option value="featured">Featured Articles</option><option value="forum">Forum</option><option value="club">Clubs</option><option value="user">Users</option></select></div><input @blur="isFocused = false" @focus="isFocused = true" @keydown.down.prevent="moveSelection(1)" @keydown.up.prevent="moveSelection(-1)" autocomplete="off" class="inputtext fl-l" id="topSearchText" name="topkeyword" placeholder="Search Anime, Manga, and more..." size="30" type="search" v-model="keyword"/><button :class="{'notActive': (keyword.length &lt; 3)}" class="fl-l" id="topSearchButon" type="submit"><i class="fa-solid fa-magnifying-glass"></i></button></form><div :style="{display: (showResult ? 'block' : 'none')}" @mousedown.prevent="" class="incrementalSearchResultList" id="topSearchResultList"><div @mouseover="selection=i" v-for="(item, i) in items"><component :focus="selection == i" :is="resolveComponent(item)" :item="item" :url="generateItemPageUrl(item)"></component></div><div :class="{'focus': selection == -1}" :style="{display: (showViewAllLink ? 'block' : 'none')}" @mouseover="selection = -1" class="list list-bottom"><a :href="resultPageUrl">
              View all results for <span class="fw-b">${ keyword }</span><i class="fa-solid fa-spinner fa-spin ml4" v-show="isRequesting"></i></a></div></div></div></div><div id="menu_left">
<ul class="js-color-pc-constant" id="nav">
<li class="small"><a class="non-link" href="#">Anime</a><ul class="x2-wider">
<li><a href="https://myanimelist.net/anime.php?_location=mal_h_m">Anime Search</a></li>
<li><a href="https://myanimelist.net/topanime.php?_location=mal_h_m">Top Anime</a></li>
<li><a href="https://myanimelist.net/anime/season?_location=mal_h_m">Seasonal Anime</a></li>
<li><a href="https://myanimelist.net/watch/episode?_location=mal_h_m_a">Videos</a></li>
<li><a href="https://myanimelist.net/reviews.php?t=anime&amp;_location=mal_h_m">Reviews</a></li>
<li><a href="https://myanimelist.net/recommendations.php?s=recentrecs&amp;t=anime&amp;_location=mal_h_m">Recommendations</a></li>

In [97]:
genre_block = None
for div in soup2.find_all("div", class_="spaceit_pad"):
    label = div.find("span", class_="dark_text")
    if label and "Genres" in label.text:
        genre_block = div
        break
genres = []
if genre_block:
    for a in genre_block.find_all("a"):
        genres.append(a.text.strip())

print(genres)

['Adventure', 'Drama', 'Fantasy']

## Al final juntamos todo y hacemos web scraping 
## en las primeras 4 páginas para obterner 200 animes:

In [ ]:
# ---- Configuración ----
base_url = "https://myanimelist.net/topanime.php"
headers = {"User-Agent": "Mozilla/5.0"}
animes = []

# ---- Recorremos 4 páginas (200 animes) ----
for offset in range(0, 200, 50):  # 0, 50, 100, 150
    url = f"{base_url}?limit={offset}" if offset > 0 else base_url
    print(f"\nScrapeando página: {url}")

    resp = requests.get(url, headers=headers)
    soup = BeautifulSoup(resp.text, "html.parser")

    details = soup.find_all('div', class_='detail')

    for detail in details:
        # ---- Título y enlace ----
        titulo_tag = detail.find('h3', class_='anime_ranking_h3')
        titulo = titulo_tag.a.text.strip() if titulo_tag and titulo_tag.a else None
        url2 = titulo_tag.a.get('href') if titulo_tag and titulo_tag.a else None

        # ---- Año ----
        info_block = detail.find('div', class_='information')
        anio = None
        if info_block:
            info_text = info_block.get_text(separator='\n').strip()
            match = re.search(r'\b(19|20)\d{2}\b', info_text)
            if match:
                anio = match.group(0)
        # ---- Géneros ----
        genres = []
        if url2:
            try:
                response2 = requests.get(url2, headers=headers)
                soup2 = BeautifulSoup(response2.content, "html.parser")

                genre_block = None
                for div in soup2.find_all("div", class_="spaceit_pad"):
                    label = div.find("span", class_="dark_text")
                    if label and "Genres" in label.text:
                        genre_block = div
                        break
                if genre_block:
                    for a in genre_block.find_all("a"):
                        genres.append(a.text.strip())
                time.sleep(1)  # Pausa entre peticiones a páginas individuales
            except Exception as e:
                print(f"Error al obtener géneros de {url2}: {e}")

        # ---- Guardamos ----
        animes.append({'titulo': titulo,'año': anio,'generos': ', '.join(genres) if genres else None})
    time.sleep(2)  # Pausa entre páginas principales para no saturar el servidor (me estaba dando errores y tiempos de espera muy largos)
    
# ---- Exportar resultados ----
df = pd.DataFrame(animes)
df.to_csv('top_animes_con_generos.csv', index=False, encoding='utf-8-sig')

print(f"\nSe han guardado {len(df)} animes en 'top_animes_con_generos.csv'")

Scrapeando página: https://myanimelist.net/topanime.php

Scrapeando página: https://myanimelist.net/topanime.php?limit=50

Scrapeando página: https://myanimelist.net/topanime.php?limit=100

Scrapeando página: https://myanimelist.net/topanime.php?limit=150

Se han guardado 200 animes en 'top_animes_con_generos.csv'

## Como los ratings me dan problemas, los voy  a sacar aparte y luego los junto

In [12]:
# Configuración
base_url = "https://myanimelist.net/topanime.php"
headers = {"User-Agent": "Mozilla/5.0"}

ratings_totales = []

# Recorrer las 4 primeras páginas (50 animes por página)
for offset in range(0, 200, 50):  # 0, 50, 100, 150
    url = f"{base_url}?limit={offset}" if offset > 0 else base_url
    print(f"Scrapeando página: {url}")
    
    resp = requests.get(url, headers=headers)
    soup = BeautifulSoup(resp.text, "html.parser")
    
    # Encontrar todos los ratings
    rating_tags = soup.find_all("span", class_=re.compile(r"score-label"))
    
    # Filtrar solo los valores numéricos
    ratings_validos = [
        r.text.strip() for r in rating_tags
        if re.match(r'^\d+(\.\d+)?$', r.text.strip())
    ]
    
    # Añadir al listado total
    ratings_totales.extend(ratings_validos)
    
    time.sleep(2)  # Pausa para no saturar el servidor

# Crear DataFrame
df_ratings = pd.DataFrame(ratings_totales, columns=['rating'])
print(df_ratings)
print(f"\nTotal de ratings recolectados: {len(df_ratings)}")

Scrapeando página: https://myanimelist.net/topanime.php
Scrapeando página: https://myanimelist.net/topanime.php?limit=50
Scrapeando página: https://myanimelist.net/topanime.php?limit=100
Scrapeando página: https://myanimelist.net/topanime.php?limit=150
    rating
0     9.29
1     9.10
2     9.07
3     9.05
4     9.05
..     ...
195   8.42
196   8.42
197   8.42
198   8.42
199   8.42

[200 rows x 1 columns]

Total de ratings recolectados: 200

In [13]:
df_ratings.head()

  rating
0   9.29
1   9.10
2   9.07
3   9.05
4   9.05

In [14]:
df_animes = pd.read_csv("C:/Users/andre\Desktop\Curso_Data_Analytics\Tercera Semana\Proyecto Anime/top_animes_con_generos.csv")

In [15]:
df_animes.head()

                               titulo   año                            generos
0                   Sousou no Frieren  2023          Adventure, Drama, Fantasy
1    Fullmetal Alchemist: Brotherhood  2009  Action, Adventure, Drama, Fantasy
2                         Steins;Gate  2011            Drama, Sci-Fi, Suspense
3  Shingeki no Kyojin Season 3 Part 2  2019            Action, Drama, Suspense
4                  Gintama: The Final  2021      Action, Comedy, Drama, Sci-Fi

In [17]:
df_animes['rating'] = df_ratings['rating']
df_animes

,titulo,año,generos,rating
0,Sousou no Frieren,2023,"Adventure, Drama, Fantasy",9.29
1,Fullmetal Alchemist: Brotherhood,2009,"Action, Adventure, Drama, Fantasy",9.10
2,Steins;Gate,2011,"Drama, Sci-Fi, Suspense",9.07
3,Shingeki no Kyojin Season 3 Part 2,2019,"Action, Drama, Suspense",9.05
4,Gintama: The Final,2021,"Action, Comedy, Drama, Sci-Fi",9.05
...,...,...,...,...
195,Wu Liuqi: Xuanwu Guo Pian,2021,"Action, Adventure, Comedy, Drama, Mystery",8.42
196,Kimetsu no Yaiba,2019,"Action, Award Winning, Supernatural",8.42
197,Kono Oto Tomare! Part 2,2019,NaN,8.42
198,Koukaku Kidoutai: Stand Alone Complex,2002,"Award Winning, Mystery, Sci-Fi",8.42
199,Mushishi Zoku Shou: Odoro no Michi,2014,"Adventure, Mystery, Slice of Life, Supernatural",8.42

In [ ]:
df_animes.to_csv('animes y género.csv', index=False)